apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-{{.Values.your_linux_username}}
  labels:
    name: {{.Values.your_linux_username}} 
spec:
  capacity:
    storage: {{.Values.nfs.server.mysql_disk_size}} 
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce  # All the pods from a single node in the openshift cluster can read & write this external storage
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{.Values.nfs.server.ip}} 
    path: {{.Values.nfs.server.mysql_shared_path}} 
