apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc-{{.Values.your_linux_username}}
spec:
  selector:
    matchLabels:
      name: {{.Values.your_linux_username}}
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{.Values.nfs.server.wordpress_disk_size}}
