apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-{{.Values.your_linux_username}}
  labels:
    name: {{.Values.your_linux_username}}
spec:
  capacity:
    storage: "{{.Values.nfs.server.wordpress_disk_size}}"
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce  # All the pods from any node in the openshift cluster can read & write this external storage
  persistentVolumeReclaimPolicy: Retain

  nfs:
    server: {{.Values.nfs.server.ip}}
    path: {{.Values.nfs.server.wordpress_shared_path}}
